# Generated by Django 3.1.7 on 2021-03-13 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210313_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='EBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('publication_date', models.DateField(verbose_name='Дата публикации')),
                ('num_pages', models.IntegerField(default=0, verbose_name='Количество страниц')),
                ('is_active', models.BooleanField(default=True)),
                ('size', models.IntegerField()),
                ('authors', models.ManyToManyField(to='main.Author')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.publisher', verbose_name='Издатель')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-publication_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HardBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('publication_date', models.DateField(verbose_name='Дата публикации')),
                ('num_pages', models.IntegerField(default=0, verbose_name='Количество страниц')),
                ('is_active', models.BooleanField(default=True)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('authors', models.ManyToManyField(to='main.Author')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.publisher', verbose_name='Издатель')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-publication_date'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
