# Generated by Django 3.1.7 on 2021-03-27 06:12

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210327_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='num_pages',
            field=models.IntegerField(default=0, validators=[main.models.num_pages_range_validation], verbose_name='Количество страниц'),
        ),
    ]
