# Generated by Django 3.1.7 on 2021-04-03 05:01

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210403_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='num_pages',
            field=models.IntegerField(default=0, validators=[main.models.num_pages_range_validation], verbose_name='Количество страниц'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
