# Generated by Django 3.1.7 on 2021-04-24 05:55

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210403_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='author_photos', validators=[utils.validators.validate_size, utils.validators.validate_extension]),
        ),
    ]
