# Generated by Django 3.1.7 on 2021-03-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='role',
            field=models.SmallIntegerField(choices=[(1, 'super admin'), (2, 'company director'), (3, 'hr manager'), (4, 'employee'), (5, 'department director')], default=4),
        ),
    ]
