USER_ROLE_SUPER_USER = 1
USER_ROLE_COMPANY_DIRECTOR = 2
USER_ROLE_HR_MANAGER = 3
USER_ROLE_EMPLOYEE = 4
USER_ROLE_DEPARTMENT_DIRECTOR = 5
USER_ROLES = (
    (USER_ROLE_SUPER_USER, 'super admin'),
    (USER_ROLE_COMPANY_DIRECTOR, 'company director'),
    (USER_ROLE_HR_MANAGER, 'hr manager'),
    (USER_ROLE_EMPLOYEE, 'employee'),
    (USER_ROLE_DEPARTMENT_DIRECTOR, 'department director'),
)
